---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker front-end image
      shell: docker pull jainpranay20/interestwin:cli

    - name: pull docker server image
      shell: docker pull jainpranay20/interestwin:ser

    - name: Create back-end container

      docker_container:
        name: backend

        image: jainpranay20/interestwin:ser

        ports:
          - "5000:5000"

    - name: Create front-end container

      docker_container:
        name: frontend

        image: jainpranay20/interestwin:cli

        interactive: true

        ports:
          - "3000:3000"
