
---
- name: Pull docker image
  hosts: all
  tasks:
    - name: copy docker compose file
      copy: 
        src: ./docker-compose.yml
        dest: ./

    - name: Start docker service
      service:
        name: docker
        state: started

    # - name: pull docker front-end image
    #   shell: docker pull jainpranay20/interestwin:cli

    # - name: pull docker server image
    #   shell: docker pull jainpranay20/interestwin:ser

    - name: docker compose pull
      command: docker-compose pull


    - name: stop previous back-end container
      shell: docker rm -f jainpranay20/interestwin:ser

    - name: stop previous front-end container
      shell: docker rm -f jainpranay20/interestwin:cli


    - name: running docker compose file
      shell: docker-compose up 
