version: "3"
services:
  react-app:
    image: jainpranay20/interestwin:cli
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: jainpranay/interestwin:ser
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
